import type { NextPage } from 'next'
import styles from '../styles/Home.module.css'
import Head from 'next/head'
import { useRouter } from 'next/router'

const Home: NextPage = () => {
  const router = useRouter()
  const { pid } = router.query

	console.log(pid);
	
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to 
        </h1>
      </main>

    </div>
  )
}

export default Home
